apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}
  namespace: testapi
spec:
  storageClassName: ubuntu-focal-golden
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: "4Gi"